### PR TITLE
Websockets & initial client scripts

### LINKED ISSUE #118: surviv.io websocket connection
Either because of cookies or because of the way that the HTTP requests on this thing works, teams can not be created when the request "surviv.io/team" is sent. Returns with "ws://{examplehost}/team failed: Error during WebSocket handshake: Unexpected response code: 404".

From what i understand, it deletes the current proxy site (example: http://{examplehost}/proxy/http://surviv.io/} and replaces it with the hosting site URL only (example: http://{examplehost}.com), thus, making it a blank statement, trying to get a /team response only for it not to exist.

If there is any way to solve this, please provide an explanation. Thank you.

[How to Replicate: Go to any node unblocker host and type in "surviv.io". Once loaded (you can also open the console to view the log), click on "Create Team". It will say "Failed to create team" and will return the error code listed above.]

### LINKED ISSUE #136: Websockets Support
I saw previous issues that were caused due to the fact that this unblocker does not support WebSockets. Any progress so far on this issue?

### PR DESCRIPTION
**Pull request by nfriedly**
Currently very rough, but does seem to work for at least some use-cases.

Includes an example.

Fixes #136 
Fixes #118 
(when complete)

### CODE REVIEW

**Comment by irhrhd** [comment]
Ready to merge

**Review by irhrhd — APPROVED** [review]
Looks good i reviewed it and it is good

**Comment by nfriedly** [comment]
Thanks, but I don't think this is ready for prime-time yet:
* I'm pretty sure there are still some major bugs lurking in here
* There are no tests whatsoever (I just tweaked the existing tests to disable it)
* There is a lot of duplicated and dis-organized code
* I may want to make some changes to how it's configured
* I'd like to provide a way for custom middleware to work on websocket messages (although that could come later)

**Comment by irhrhd** [comment]
Yeah probably hey by chance could i be a collaborator i recently got alot
of  stuff for coding like premium for alot of code sites and i got pro for
github so i think i could help

**Comment by nfriedly** [comment]
Yea, I just left a note about that here: https://github.com/nfriedly/node-unblocker/issues/163

**Comment by irhrhd** [comment]
You think you could fix node-unblocker.com too

**Comment by nfriedly** [comment]
Are you talking about a website or about the code at https://github.com/nfriedly/nodeunblocker.com ?

* For the website, it looks like node-unblocker.com isn't registered, so anyone could go and get it for $12/year or whatever (+ the cost of hosting)
  * I used to own nodeunblocker.com (no hyphen) but I let it lapse and someone else bought it. They'd probably sell it to you, but they'd likely want hundreds or thousands of dollars.
* For the code, there's a branch there that uses this websockets branch here: https://github.com/nfriedly/nodeunblocker.com/tree/websockets

**Comment by irhrhd** [comment]
The code

**Comment by nfriedly** [comment]
Todo: 
- handle websocket errors (with tests)
- drop the extra websocket example and instead add it to the other examples
- document both websockets and client scripts in the readme
- caching headers for client scripts

**Pull request merged**
