### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by real-cereal-boy**

### CODE REVIEW

**Comment by emilhem** [comment]
Why is this needed? The AGPLv3 license already have a liability clause.

Also there is no requirement from anyone to support the software, regardless of version.

**Comment by real-cereal-boy** [comment]
Sorry just thought you

**Comment by real-cereal-boy** [comment]
Can you help me with issue #124 ?

**Comment by nfriedly** [comment]
I agree with @emilhem, going to close this. Thanks for trying to help, though, I do appreciate the effort.

**Pull request closed without merging**
