### PR TITLE
Fix for double percent-encoding for cookies

### PR DESCRIPTION
**Pull request by emilhem**
Includes tests! :)

### CODE REVIEW

**Comment by nfriedly** [comment]
Again, great work, thanks!

**Comment by nfriedly** [comment]
BTW, I'm putting out `v1.1.3` with your fixes in case you want to use the npm version. Travis CI should publish it after the tests pass.

**Comment by emilhem** [comment]
Great should I add 1.1.3 to package.json to my pull request?

**Comment by nfriedly** [comment]
No, sorry, I thought I had already merged this one :/

The package.json update is automatic.

**Comment by nfriedly** [comment]
So, this will now go live in `v1.1.4` :p

**Pull request merged**
